spring:
  datasource:
    url: jdbc:mysql://uclee-mysql.mysql.database.azure.com:3306/security_and_privacy
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ie_mysql
    password: virmer-7fywse-wiRzut
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


  resources:
    static-locations=classpath:/static: